// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyleTee.Data;

#nullable disable

namespace StyleTee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250317082231_okok")]
    partial class okok
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StyleTee.Models.ChatLieu", b =>
                {
                    b.Property<Guid>("ID_ChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_ChatLieu");

                    b.ToTable("ChatLieu");
                });

            modelBuilder.Entity("StyleTee.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("ID_DanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_DanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("StyleTee.Models.DiaChi", b =>
                {
                    b.Property<Guid>("ID_DiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_TaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tinhThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DiaChi");

                    b.HasIndex("ID_TaiKhoan");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("StyleTee.Models.GioHang", b =>
                {
                    b.Property<Guid>("ID_GioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_TaiKhoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_GioHang");

                    b.HasIndex("ID_TaiKhoan");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("StyleTee.Models.GioHangChiTiet", b =>
                {
                    b.Property<Guid>("ID_GioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_GioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_SanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("donGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.HasKey("ID_GioHangChiTiet");

                    b.HasIndex("ID_GioHang");

                    b.HasIndex("ID_SanPhamChiTiet");

                    b.ToTable("GioHangChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.HinhAnh", b =>
                {
                    b.Property<Guid>("ID_HinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_SanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("url_hinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_HinhAnh");

                    b.HasIndex("ID_SanPhamChiTiet");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("StyleTee.Models.KichThuoc", b =>
                {
                    b.Property<Guid>("ID_KichThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenKichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_KichThuoc");

                    b.ToTable("KichThuoc");
                });

            modelBuilder.Entity("StyleTee.Models.KieuDang", b =>
                {
                    b.Property<Guid>("ID_KieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenKieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_KieuDang");

                    b.ToTable("KieuDang");
                });

            modelBuilder.Entity("StyleTee.Models.MauSac", b =>
                {
                    b.Property<Guid>("ID_MauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenMauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_MauSac");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("StyleTee.Models.PhieuGiamGiaVaKhuyenMai.KhuyenMai", b =>
                {
                    b.Property<Guid>("ID_KhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TyLeKhuyenMai")
                        .HasColumnType("int");

                    b.HasKey("ID_KhuyenMai");

                    b.HasIndex("TyLeKhuyenMai", "NgayBatDau")
                        .IsUnique()
                        .HasDatabaseName("UQ_TyLeKhuyenMai");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("StyleTee.Models.PhieuGiamGiaVaKhuyenMai.PhieuGiamGia", b =>
                {
                    b.Property<Guid>("Ma_PhieuGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaTriDonHangToiThieu")
                        .HasColumnType("float");

                    b.Property<double>("GiaTriKhuyenMai")
                        .HasColumnType("float");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongToiDaCho1Nguoi")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTong")
                        .HasColumnType("int");

                    b.Property<string>("TenPhieuGiamGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma_PhieuGiamGia");

                    b.HasIndex("TenPhieuGiamGia")
                        .IsUnique()
                        .HasDatabaseName("UQ_TenPhieuGiamGia");

                    b.ToTable("PhieuGiamGia");
                });

            modelBuilder.Entity("StyleTee.Models.SanPham", b =>
                {
                    b.Property<Guid>("ID_SanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_DanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("giaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SanPham");

                    b.HasIndex("ID_DanhMuc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("StyleTee.Models.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("ID_SanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_ChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_KieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Mau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_SanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Size")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_ThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_XuatXu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("giaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ngayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("soLuongTon")
                        .HasColumnType("int");

                    b.HasKey("ID_SanPhamChiTiet");

                    b.HasIndex("ID_ChatLieu");

                    b.HasIndex("ID_KieuDang");

                    b.HasIndex("ID_Mau");

                    b.HasIndex("ID_SanPham");

                    b.HasIndex("ID_Size");

                    b.HasIndex("ID_ThuongHieu");

                    b.HasIndex("ID_XuatXu");

                    b.ToTable("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("ID_TaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("StyleTee.Models.ThuongHieu", b =>
                {
                    b.Property<Guid>("ID_ThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_ThuongHieu");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("StyleTee.Models.XuatXu", b =>
                {
                    b.Property<Guid>("ID_XuatXu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tenXuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("trangThai")
                        .HasColumnType("bit");

                    b.HasKey("ID_XuatXu");

                    b.ToTable("XuatXu");
                });

            modelBuilder.Entity("StyleTee.Models.DiaChi", b =>
                {
                    b.HasOne("StyleTee.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DiaChis")
                        .HasForeignKey("ID_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("StyleTee.Models.GioHang", b =>
                {
                    b.HasOne("StyleTee.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("GioHang")
                        .HasForeignKey("ID_TaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("StyleTee.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("StyleTee.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiet")
                        .HasForeignKey("ID_GioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("ID_SanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.HinhAnh", b =>
                {
                    b.HasOne("StyleTee.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("HinhAnh")
                        .HasForeignKey("ID_SanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.SanPham", b =>
                {
                    b.HasOne("StyleTee.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPham")
                        .HasForeignKey("ID_DanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("StyleTee.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("StyleTee.Models.ChatLieu", "ChatLieu")
                        .WithMany("SanPhamChiTiet")
                        .HasForeignKey("ID_ChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.KieuDang", "KieuDang")
                        .WithMany("SanPhamChiTiet")
                        .HasForeignKey("ID_KieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("ID_Mau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiet")
                        .HasForeignKey("ID_SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.KichThuoc", "KichThuoc")
                        .WithMany("SanPhamChiTiet")
                        .HasForeignKey("ID_Size")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhamChiTiet")
                        .HasForeignKey("ID_ThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleTee.Models.XuatXu", "XuatXu")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("ID_XuatXu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("KichThuoc");

                    b.Navigation("KieuDang");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("ThuongHieu");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("StyleTee.Models.ChatLieu", b =>
                {
                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("StyleTee.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.KichThuoc", b =>
                {
                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.KieuDang", b =>
                {
                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("StyleTee.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("GioHangChiTiets");

                    b.Navigation("HinhAnh");
                });

            modelBuilder.Entity("StyleTee.Models.TaiKhoan", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("StyleTee.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("StyleTee.Models.XuatXu", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
